#!/bin/sh
case "$1" in
  start)
    $0 stop
    pactl load-module module-simple-protocol-tcp rate=44100 format=s16le channels=2 source=$(pactl list | grep "Monitor Source" | awk '{print $3}') record=true port=12345;
    echo "Port: 12345"
    ;;
  stop)
    pactl unload-module `pactl list | grep tcp -B1 | grep M | sed 's/[^0-9]//g'`
    ;;
  *)
    echo "Usage: $0 start|stop" >&2
    ;;
esac
